version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - RAILS_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_ADMIN_SDK_CREDENTIALS=${FIREBASE_ADMIN_SDK_CREDENTIALS}
    volumes:
      - ./backend:/rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0